.PHONY: clean All

All:
	@echo "----------Building project:[ enthral - Debug ]----------"
	@cd "enthral" && "$(MAKE)" -f  "enthral.mk"
clean:
	@echo "----------Cleaning project:[ enthral - Debug ]----------"
	@cd "enthral" && "$(MAKE)" -f  "enthral.mk" clean
